name: camera_example
description: Demonstrates how to use the camera plugin.

dependencies:
  flutter_better_camera:
    path: ../
  path_provider: ^0.5.0
  flutter:
    sdk: flutter
  video_player: ^0.10.0
  fdottedline: ^1.0.1
  flutter_svg: ^0.19.1
  device_preview: ^0.4.8
  permission_handler: ^5.1.0+2
  e2e: "^0.2.0"

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_driver:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
   
    - assets/camera/

environment:
  sdk: ">=2.0.0-dev.28.0 <3.0.0"
  flutter: ">=1.9.1+hotfix.4 <2.0.0"
